// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_O4eDz8eRT6-CweEkeLVkQecjmfzV2hc',
    appId: '1:159724613309:web:0c734de0bbcb9c04ed91d4',
    messagingSenderId: '159724613309',
    projectId: 'betel-app',
    authDomain: 'betel-app.firebaseapp.com',
    storageBucket: 'betel-app.appspot.com',
    measurementId: 'G-D82DE0H8D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYNyMfKUqfp8flyBZs92x96iDoa5YT-M',
    appId: '1:159724613309:android:5de38c77be63e44fed91d4',
    messagingSenderId: '159724613309',
    projectId: 'betel-app',
    storageBucket: 'betel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFlRX2s-s9zePp2eaRokKgLBlQ6SVeZc',
    appId: '1:159724613309:ios:ebd9e92fbe3bab26ed91d4',
    messagingSenderId: '159724613309',
    projectId: 'betel-app',
    storageBucket: 'betel-app.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFlRX2s-s9zePp2eaRokKgLBlQ6SVeZc',
    appId: '1:159724613309:ios:2074810c3aa6d64ded91d4',
    messagingSenderId: '159724613309',
    projectId: 'betel-app',
    storageBucket: 'betel-app.appspot.com',
    iosBundleId: 'com.example.myFirstApp.RunnerTests',
  );
}
